version: "3"
services:
  api:
    build:
      context: ./docker
      dockerfile: Dockerfile.api
    env_file:
      - ./.env
  client:
    build:
      context: ./docker
      dockerfile: Dockerfile.client
    env_file:
      - ./.env