version: '3'

services:
  client:
    extends:
      file: docker-compose.base.yml
      service: nx-app-base
    command: npm run dev:client
    ports:
      - 4200:4200

  server:
    extends:
      file: docker-compose.base.yml
      service: nx-app-base
    command: npm run dev:server
    ports:
      - 3333:3333

volumes:
  mono-node-modules: null