version: "3"

services:
  nx-app-base:
    restart: always
    build:
      context: ./docker
      dockerfile: Dockerfile
    environment:
      - DEV_PLATFORM=DOCKER
    env_file:
      - ./.env
    volumes:
      - ./:/app
      - mono-node-modules:/app/node_modules